-- MySQL Script generated by MySQL Workbench
-- Tue Nov 26 09:38:03 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ssafytrip
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ssafytrip
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ssafytrip` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ssafytrip` ;

-- -----------------------------------------------------
-- Table `ssafytrip`.`sidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssafytrip`.`sidos` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `sido_code` INT NULL DEFAULT NULL,
  `sido_name` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`no`),
  UNIQUE INDEX `sido_code_UNIQUE` (`sido_code` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ssafytrip`.`guguns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssafytrip`.`guguns` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `sido_code` INT NULL DEFAULT NULL,
  `gugun_code` INT NULL DEFAULT NULL,
  `gugun_name` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`no`),
  INDEX `guguns_sido_to_sidos_cdoe_fk_idx` (`sido_code` ASC) VISIBLE,
  INDEX `gugun_code_idx` (`gugun_code` ASC) VISIBLE,
  CONSTRAINT `guguns_sido_to_sidos_cdoe_fk`
    FOREIGN KEY (`sido_code`)
    REFERENCES `ssafytrip`.`sidos` (`sido_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ssafytrip`.`contenttypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssafytrip`.`contenttypes` (
  `content_type_id` INT NOT NULL,
  `content_type_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`content_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ssafytrip`.`attractions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssafytrip`.`attractions` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `content_id` INT NULL DEFAULT NULL,
  `title` VARCHAR(500) NULL DEFAULT NULL,
  `content_type_id` INT NULL DEFAULT NULL,
  `area_code` INT NULL DEFAULT NULL,
  `si_gun_gu_code` INT NULL DEFAULT NULL,
  `first_image1` VARCHAR(100) NULL DEFAULT NULL,
  `first_image2` VARCHAR(100) NULL DEFAULT NULL,
  `map_level` INT NULL DEFAULT NULL,
  `latitude` DECIMAL(20,17) NULL DEFAULT NULL,
  `longitude` DECIMAL(20,17) NULL DEFAULT NULL,
  `tel` VARCHAR(20) NULL DEFAULT NULL,
  `addr1` VARCHAR(100) NULL DEFAULT NULL,
  `addr2` VARCHAR(100) NULL DEFAULT NULL,
  `homepage` VARCHAR(1000) NULL DEFAULT NULL,
  `overview` VARCHAR(10000) NULL DEFAULT NULL,
  PRIMARY KEY (`no`),
  INDEX `attractions_typeid_to_types_typeid_fk_idx` (`content_type_id` ASC) VISIBLE,
  INDEX `attractions_sido_to_sidos_code_fk_idx` (`area_code` ASC) VISIBLE,
  INDEX `attractions_sigungu_to_guguns_gugun_fk_idx` (`si_gun_gu_code` ASC) VISIBLE,
  CONSTRAINT `attractions_area_to_sidos_code_fk`
    FOREIGN KEY (`area_code`)
    REFERENCES `ssafytrip`.`sidos` (`sido_code`),
  CONSTRAINT `attractions_sigungu_to_guguns_gugun_fk`
    FOREIGN KEY (`si_gun_gu_code`)
    REFERENCES `ssafytrip`.`guguns` (`gugun_code`),
  CONSTRAINT `attractions_typeid_to_types_typeid_fk`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `ssafytrip`.`contenttypes` (`content_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ssafytrip`.`members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssafytrip`.`members` (
  `user_id` VARCHAR(16) NOT NULL,
  `role` VARCHAR(45) NOT NULL DEFAULT 'USER',
  `user_name` VARCHAR(20) NOT NULL,
  `user_password` VARCHAR(16) NOT NULL,
  `email_id` VARCHAR(20) NOT NULL,
  `email_domain` VARCHAR(45) NOT NULL,
  `gender` TINYINT(1) NOT NULL,
  `birth` VARCHAR(10) NOT NULL,
  `profile_url` VARCHAR(2083) NULL DEFAULT NULL,
  `join_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `token` VARCHAR(2083) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ssafytrip`.`tripdiarys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssafytrip`.`tripdiarys` (
  `diary_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(16) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `content` TEXT NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  `has_map` TINYINT(1) NOT NULL,
  `is_public` TINYINT(1) NOT NULL DEFAULT '0',
  `total_days` INT NOT NULL,
  `thumbnailUrl` VARCHAR(2083) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`diary_id`),
  INDEX `fk_tripdiarys_members_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_tripdiarys_members`
    FOREIGN KEY (`user_id`)
    REFERENCES `ssafytrip`.`members` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ssafytrip`.`diarylikes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssafytrip`.`diarylikes` (
  `like_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(16) NOT NULL,
  `diary_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`like_id`),
  UNIQUE INDEX `unique_diary_like_UNIQUE` (`user_id` ASC, `diary_id` ASC) VISIBLE,
  INDEX `fk_diarylikes_members1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_diarylikes_tripdiarys1_idx` (`diary_id` ASC) VISIBLE,
  CONSTRAINT `fk_diarylikes_members1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ssafytrip`.`members` (`user_id`),
  CONSTRAINT `fk_diarylikes_tripdiarys1`
    FOREIGN KEY (`diary_id`)
    REFERENCES `ssafytrip`.`tripdiarys` (`diary_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ssafytrip`.`follows`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssafytrip`.`follows` (
  `follow_id` INT NOT NULL AUTO_INCREMENT,
  `follower_id` VARCHAR(16) NOT NULL,
  `following_id` VARCHAR(16) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`follow_id`),
  UNIQUE INDEX `unique_follow_UNIQUE` (`follower_id` ASC, `following_id` ASC) INVISIBLE,
  INDEX `fk_members_has_members_members2_idx` (`following_id` ASC) VISIBLE,
  INDEX `fk_members_has_members_members1_idx` (`follower_id` ASC) VISIBLE,
  CONSTRAINT `fk_members_has_members_members1`
    FOREIGN KEY (`follower_id`)
    REFERENCES `ssafytrip`.`members` (`user_id`),
  CONSTRAINT `fk_members_has_members_members2`
    FOREIGN KEY (`following_id`)
    REFERENCES `ssafytrip`.`members` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ssafytrip`.`keywordhistories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssafytrip`.`keywordhistories` (
  `history_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(16) NOT NULL,
  `keyword` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`history_id`),
  INDEX `fk_keywordhistories_members1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_keywordhistories_members1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ssafytrip`.`members` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ssafytrip`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssafytrip`.`messages` (
  `message_id` INT NOT NULL AUTO_INCREMENT,
  `sender_id` VARCHAR(16) NOT NULL,
  `receiver_id` VARCHAR(16) NOT NULL,
  `content` TEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`message_id`),
  INDEX `fk_members_has_members_members4_idx` (`receiver_id` ASC) VISIBLE,
  INDEX `fk_members_has_members_members3_idx` (`sender_id` ASC) VISIBLE,
  CONSTRAINT `fk_members_has_members_members3`
    FOREIGN KEY (`sender_id`)
    REFERENCES `ssafytrip`.`members` (`user_id`),
  CONSTRAINT `fk_members_has_members_members4`
    FOREIGN KEY (`receiver_id`)
    REFERENCES `ssafytrip`.`members` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ssafytrip`.`triproutes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssafytrip`.`triproutes` (
  `route_id` INT NOT NULL AUTO_INCREMENT,
  `diary_id` INT NOT NULL,
  `attractions_no` INT NOT NULL,
  `detail_start_time` VARCHAR(10) NULL DEFAULT NULL,
  `detail_end_time` VARCHAR(10) NULL DEFAULT NULL,
  `day` INT NULL DEFAULT NULL,
  `visit_order` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`route_id`),
  INDEX `fk_triproutes_tripdiarys1_idx` (`diary_id` ASC) VISIBLE,
  INDEX `fk_triproutes_attractions1_idx` (`attractions_no` ASC) VISIBLE,
  CONSTRAINT `fk_triproutes_attractions1`
    FOREIGN KEY (`attractions_no`)
    REFERENCES `ssafytrip`.`attractions` (`no`),
  CONSTRAINT `fk_triproutes_tripdiarys1`
    FOREIGN KEY (`diary_id`)
    REFERENCES `ssafytrip`.`tripdiarys` (`diary_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
